-- ========================================================
-- PAKETSHOP - SUPABASE SCHEMA INITIALIZATION
-- Fresh setup schema with admin-safe RLS defaults
-- ========================================================

create extension if not exists pgcrypto;

-- 1. Categories
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique,
  image text not null,
  description text default '',
  "googleProductCategory" text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Products
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price bigint not null,
  image text not null,
  category text not null,
  "categoryId" bigint references public.categories(id) on delete set null,
  description text,
  stock integer default 0,
  "itemsPerPackage" integer default 1,
  images text[] default '{}',
  "videoUrl" text,
  specifications jsonb default '[]'::jsonb,
  is_premium boolean default false,
  is_bestseller boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Orders
create table if not exists public.orders (
  id text primary key,
  "customerName" text not null,
  phone text not null,
  total bigint not null,
  status text default 'Kutilmoqda',
  "paymentMethod" text not null,
  date text not null,
  user_id uuid references auth.users(id) on delete set null,
  items jsonb default '[]'::jsonb,
  shipping_address text,
  city text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Wishlist
create table if not exists public.wishlists (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, product_id)
);

-- 5. Blog posts
create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  image text not null,
  content text not null,
  date text not null,
  seo jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Hero content
create table if not exists public.hero_content (
  id text primary key default 'main',
  badge text,
  title text,
  description text,
  "buttonText" text,
  images text[] default '{}',
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Navigation settings
create table if not exists public.navigation_settings (
  id text primary key default 'main',
  "menuItems" jsonb default '[]'::jsonb,
  "socialLinks" jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. Chat leads
create table if not exists public.leads (
  id text primary key,
  name text not null,
  phone text not null,
  last_message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 9. Admin registry
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ========================================================
-- ADMIN HELPER FUNCTION
-- Add an auth user into public.admin_users via SQL editor to grant admin access
-- ========================================================

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

-- ========================================================
-- ROW LEVEL SECURITY
-- ========================================================

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.wishlists enable row level security;
alter table public.blog_posts enable row level security;
alter table public.hero_content enable row level security;
alter table public.navigation_settings enable row level security;
alter table public.leads enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "Public categories are viewable" on public.categories;
drop policy if exists "Public products are viewable" on public.products;
drop policy if exists "Public blogs are viewable" on public.blog_posts;
drop policy if exists "Public hero viewable" on public.hero_content;
drop policy if exists "Public nav viewable" on public.navigation_settings;
drop policy if exists "Allow all access categories" on public.categories;
drop policy if exists "Allow all access products" on public.products;
drop policy if exists "Allow all access blogs" on public.blog_posts;
drop policy if exists "Allow all access hero" on public.hero_content;
drop policy if exists "Allow all access nav" on public.navigation_settings;
drop policy if exists "Anyone can insert an order" on public.orders;
drop policy if exists "Users can view their own orders" on public.orders;
drop policy if exists "Users can view their own wishlist" on public.wishlists;
drop policy if exists "Users can insert into their own wishlist" on public.wishlists;
drop policy if exists "Users can delete from their own wishlist" on public.wishlists;
drop policy if exists "Public read categories" on public.categories;
drop policy if exists "Public read products" on public.products;
drop policy if exists "Public read blog posts" on public.blog_posts;
drop policy if exists "Public read hero content" on public.hero_content;
drop policy if exists "Public read navigation settings" on public.navigation_settings;
drop policy if exists "Admins manage categories" on public.categories;
drop policy if exists "Admins manage products" on public.products;
drop policy if exists "Admins manage blog posts" on public.blog_posts;
drop policy if exists "Admins manage hero content" on public.hero_content;
drop policy if exists "Admins manage navigation settings" on public.navigation_settings;
drop policy if exists "Guests can create orders" on public.orders;
drop policy if exists "Users view own orders" on public.orders;
drop policy if exists "Admins manage orders" on public.orders;
drop policy if exists "Users view own wishlist" on public.wishlists;
drop policy if exists "Users insert own wishlist" on public.wishlists;
drop policy if exists "Users delete own wishlist" on public.wishlists;
drop policy if exists "Public create leads" on public.leads;
drop policy if exists "Admins manage leads" on public.leads;
drop policy if exists "Users can view own admin membership" on public.admin_users;

create policy "Public read categories"
  on public.categories for select
  using (true);

create policy "Public read products"
  on public.products for select
  using (true);

create policy "Public read blog posts"
  on public.blog_posts for select
  using (true);

create policy "Public read hero content"
  on public.hero_content for select
  using (true);

create policy "Public read navigation settings"
  on public.navigation_settings for select
  using (true);

create policy "Admins manage categories"
  on public.categories for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins manage products"
  on public.products for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins manage blog posts"
  on public.blog_posts for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins manage hero content"
  on public.hero_content for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins manage navigation settings"
  on public.navigation_settings for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "Guests can create orders"
  on public.orders for insert
  with check (user_id is null or auth.uid() = user_id);

create policy "Users view own orders"
  on public.orders for select
  using (auth.uid() = user_id);

create policy "Admins manage orders"
  on public.orders for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "Users view own wishlist"
  on public.wishlists for select
  using (auth.uid() = user_id);

create policy "Users insert own wishlist"
  on public.wishlists for insert
  with check (auth.uid() = user_id);

create policy "Users delete own wishlist"
  on public.wishlists for delete
  using (auth.uid() = user_id);

create policy "Public create leads"
  on public.leads for insert
  with check (true);

create policy "Admins manage leads"
  on public.leads for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "Users can view own admin membership"
  on public.admin_users for select
  using (auth.uid() = user_id or public.is_admin());
