-- ========================================================
-- PAKETSHOP - SUPABASE SCHEMA INITIALIZATION
-- ========================================================

-- 1. Create Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    image TEXT NOT NULL,
    icon TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price BIGINT NOT NULL,
    image TEXT NOT NULL,
    category TEXT NOT NULL,
    "categoryId" BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    description TEXT,
    stock INTEGER DEFAULT 0,
    "itemsPerPackage" INTEGER DEFAULT 1,
    images TEXT[] DEFAULT '{}',
    specifications JSONB DEFAULT '{}',
    is_premium BOOLEAN DEFAULT FALSE,
    is_bestseller BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id TEXT PRIMARY KEY,
    "customerName" TEXT NOT NULL,
    phone TEXT NOT NULL,
    total BIGINT NOT NULL,
    status TEXT DEFAULT 'Kutilmoqda',
    "paymentMethod" TEXT NOT NULL,
    date TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    items JSONB DEFAULT '[]',
    shipping_address TEXT,
    city TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Create Wishlist Table (For logged in users)
CREATE TABLE IF NOT EXISTS public.wishlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(user_id, product_id)
);

-- 5. Create Blog Posts Table
CREATE TABLE IF NOT EXISTS public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    image TEXT NOT NULL,
    content TEXT NOT NULL,
    date TEXT NOT NULL,
    seo_title TEXT,
    seo_description TEXT,
    seo_keywords TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 6. Create Hero Content (Banner) Table
CREATE TABLE IF NOT EXISTS public.hero_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    badge TEXT,
    title TEXT,
    description TEXT,
    "buttonText" TEXT,
    images TEXT[] DEFAULT '{}',
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 7. Create Navigation Settings Table
CREATE TABLE IF NOT EXISTS public.navigation_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logo_text TEXT,
    phone_number TEXT,
    address TEXT,
    working_hours TEXT,
    instagram_url TEXT,
    telegram_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ========================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ========================================================

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hero_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.navigation_settings ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Public products are viewable" ON public.products FOR SELECT USING (true);
CREATE POLICY "Public categories are viewable" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Public blogs are viewable" ON public.blog_posts FOR SELECT USING (true);
CREATE POLICY "Public hero viewable" ON public.hero_content FOR SELECT USING (true);
CREATE POLICY "Public nav viewable" ON public.navigation_settings FOR SELECT USING (true);

-- TEMPORARY: Allow all insert/update to make admin panel easy without complex auth
CREATE POLICY "Allow all access products" ON public.products FOR ALL USING (true);
CREATE POLICY "Allow all access categories" ON public.categories FOR ALL USING (true);
CREATE POLICY "Allow all access blogs" ON public.blog_posts FOR ALL USING (true);
CREATE POLICY "Allow all access hero" ON public.hero_content FOR ALL USING (true);
CREATE POLICY "Allow all access nav" ON public.navigation_settings FOR ALL USING (true);

-- Allow inserting orders for everyone (guest checkout)
CREATE POLICY "Anyone can insert an order" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can view their own orders" ON public.orders FOR SELECT USING (true); -- simplified for now

-- Wishlist access control
CREATE POLICY "Users can view their own wishlist" ON public.wishlists FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert into their own wishlist" ON public.wishlists FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete from their own wishlist" ON public.wishlists FOR DELETE USING (auth.uid() = user_id);
