'use client';
import React, { useEffect, useMemo, useState } from 'react';
import { Archive, Edit3, Loader2, Plus, RefreshCw, X } from 'lucide-react';
import { slugify } from '@/lib/slugify';

interface CategoryOption { id: string; translations: Array<{ locale: string; name: string }> }
interface ProductRecord {
  id: string; sku: string; slugUz: string; slugRu: string; categoryId: string; status: string; availabilityStatus: string; priceMode: string; baseUnit: string; saleUnit: string; unitsPerPack: number; packsPerCarton: number; unitsPerCarton: number; minimumOrderQuantity: number; orderStep: number; publicPrice: string | number | null; originCountry?: string | null; isFeatured: boolean; isNew: boolean; isBestSeller: boolean; isSeasonal: boolean; translations: Array<{ locale: string; name: string; shortDescription?: string | null; description?: string | null }>; variants: Array<Record<string, unknown>>; priceTiers: Array<Record<string, unknown>>;
}

const initialForm = { sku: '', nameUz: '', nameRu: '', categoryId: '', publicPrice: '', unitsPerPack: 1, packsPerCarton: 1, minimumOrderQuantity: 1, orderStep: 1, saleUnit: 'PACK', availabilityStatus: 'CHECK_AVAILABILITY', priceMode: 'PUBLIC_EXACT', originCountry: '' };

export default function AdminProductsV2() {
  const [products, setProducts] = useState<ProductRecord[]>([]); const [categories, setCategories] = useState<CategoryOption[]>([]); const [form, setForm] = useState(initialForm); const [editing, setEditing] = useState<ProductRecord | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [query, setQuery] = useState('');
  const categoryName = useMemo(() => new Map(categories.map((category) => [category.id, category.translations.find((translation) => translation.locale === 'uz')?.name || category.id])), [categories]);

  const load = async () => { setLoading(true); setError(''); try { const [productsResponse, categoriesResponse] = await Promise.all([fetch(`/api/admin/products?q=${encodeURIComponent(query)}`), fetch('/api/admin/categories')]); const productsResult = await productsResponse.json(); const categoriesResult = await categoriesResponse.json(); if (!productsResponse.ok || !categoriesResponse.ok) throw new Error(productsResult.error || categoriesResult.error || 'Ma’lumot yuklanmadi'); setProducts(productsResult.products); setCategories(categoriesResult.categories); setForm((current) => ({ ...current, categoryId: current.categoryId || categoriesResult.categories[0]?.id || '' })); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Xatolik'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);

  const edit = (product: ProductRecord) => { const uz = product.translations.find((translation) => translation.locale === 'uz'); const ru = product.translations.find((translation) => translation.locale === 'ru'); setEditing(product); setForm({ sku: product.sku, nameUz: uz?.name || '', nameRu: ru?.name || '', categoryId: product.categoryId, publicPrice: product.publicPrice == null ? '' : String(product.publicPrice), unitsPerPack: product.unitsPerPack, packsPerCarton: product.packsPerCarton, minimumOrderQuantity: product.minimumOrderQuantity, orderStep: product.orderStep, saleUnit: product.saleUnit, availabilityStatus: product.availabilityStatus, priceMode: product.priceMode, originCountry: product.originCountry || '' }); };
  const reset = () => { setEditing(null); setForm({ ...initialForm, categoryId: categories[0]?.id || '' }); };

  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); const slugUz = slugify(form.nameUz); const payload = { sku: form.sku, slugUz, slugRu: `${slugUz}-ru`, categoryId: form.categoryId, status: 'ACTIVE', availabilityStatus: form.availabilityStatus, priceMode: form.priceMode, baseUnit: 'PIECE', saleUnit: form.saleUnit, unitsPerPack: form.unitsPerPack, packsPerCarton: form.packsPerCarton, unitsPerCarton: form.unitsPerPack * form.packsPerCarton, minimumOrderQuantity: form.minimumOrderQuantity, orderStep: form.orderStep, publicPrice: form.publicPrice === '' ? null : Number(form.publicPrice), originCountry: form.originCountry || null, name: { uz: form.nameUz, ru: form.nameRu }, shortDescription: editing ? { uz: editing.translations.find((translation) => translation.locale === 'uz')?.shortDescription || '', ru: editing.translations.find((translation) => translation.locale === 'ru')?.shortDescription || '' } : undefined, description: editing ? { uz: editing.translations.find((translation) => translation.locale === 'uz')?.description || '', ru: editing.translations.find((translation) => translation.locale === 'ru')?.description || '' } : undefined, isFeatured: editing?.isFeatured || false, isNew: editing?.isNew || false, isBestSeller: editing?.isBestSeller || false, isSeasonal: editing?.isSeasonal || false, variants: editing?.variants || [], priceTiers: editing?.priceTiers || [] };
    try { const response = await fetch(editing ? `/api/admin/products/${editing.id}` : '/api/admin/products', { method: editing ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Mahsulot saqlanmadi'); reset(); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : 'Xatolik'); } finally { setSaving(false); } };
  const archive = async (id: string) => { if (!window.confirm('Mahsulotni arxivlashni tasdiqlaysizmi?')) return; const response = await fetch(`/api/admin/products/${id}`, { method: 'DELETE' }); if (response.ok) await load(); else setError('Mahsulot arxivlanmadi'); };

  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">B2B mahsulotlar</h2><p className="text-sm text-slate-500">SKU, qadoq, korobka va narx birligi</p></div><div className="flex gap-2"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="SKU yoki nom" className="rounded-xl border border-slate-200 bg-white px-3 py-2" /><button onClick={() => void load()} className="rounded-xl border border-slate-200 p-2.5"><RefreshCw size={18} /></button></div></div>
    {error && <div className="rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}
    <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold">{editing ? `${editing.sku} ni tahrirlash` : 'Yangi mahsulot'}</h3>{editing && <button type="button" onClick={reset} className="p-1 text-slate-500"><X size={18} /></button>}</div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">
      <input required value={form.sku} onChange={(e) => setForm({ ...form, sku: e.target.value.toUpperCase() })} placeholder="SKU" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5" /><input required value={form.nameUz} onChange={(e) => setForm({ ...form, nameUz: e.target.value })} placeholder="O‘zbekcha nom" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5" /><input required value={form.nameRu} onChange={(e) => setForm({ ...form, nameRu: e.target.value })} placeholder="Русское название" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5" /><select required value={form.categoryId} onChange={(e) => setForm({ ...form, categoryId: e.target.value })} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5"><option value="">Kategoriya</option>{categories.filter((category) => (category as CategoryOption & { active?: boolean }).active !== false).map((category) => <option key={category.id} value={category.id}>{categoryName.get(category.id)}</option>)}</select>
      <input type="number" min="0" value={form.publicPrice} onChange={(e) => setForm({ ...form, publicPrice: e.target.value })} placeholder="1 qadoq narxi" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5" /><input type="number" min="1" value={form.unitsPerPack} onChange={(e) => setForm({ ...form, unitsPerPack: Number(e.target.value) })} placeholder="Qadoqdagi dona" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5" /><input type="number" min="1" value={form.packsPerCarton} onChange={(e) => setForm({ ...form, packsPerCarton: Number(e.target.value) })} placeholder="Korobkadagi qadoq" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5" /><input value={form.originCountry} onChange={(e) => setForm({ ...form, originCountry: e.target.value })} placeholder="Ishlab chiqarilgan mamlakat" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5" />
      <select value={form.saleUnit} onChange={(e) => setForm({ ...form, saleUnit: e.target.value })} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5"><option value="PACK">Qadoq</option><option value="CARTON">Korobka</option><option value="PIECE">Dona</option><option value="ROLL">Rulon</option><option value="KILOGRAM">Kilogramm</option></select><select value={form.availabilityStatus} onChange={(e) => setForm({ ...form, availabilityStatus: e.target.value })} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5"><option value="IN_STOCK">Omborda mavjud</option><option value="LOW_STOCK">Kam qoldi</option><option value="CHECK_AVAILABILITY">Qoldiqni aniqlash</option><option value="ON_ORDER">Buyurtma asosida</option><option value="OUT_OF_STOCK">Vaqtincha yo‘q</option></select><select value={form.priceMode} onChange={(e) => setForm({ ...form, priceMode: e.target.value })} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5"><option value="PUBLIC_EXACT">Aniq narx</option><option value="FROM_PRICE">...dan</option><option value="REQUEST_ONLY">Narxni so‘rash</option></select><button disabled={saving || !form.categoryId} className="flex items-center justify-center gap-2 rounded-xl bg-red-600 px-4 py-2.5 font-bold text-black disabled:opacity-50">{saving ? <Loader2 className="animate-spin" size={18} /> : <Plus size={18} />}{editing ? 'Saqlash' : 'Qo‘shish'}</button>
    </div></form>
    <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white">{loading ? <div className="p-10 text-center"><Loader2 className="mx-auto animate-spin" /></div> : <table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-3">SKU</th><th className="p-3">Mahsulot</th><th className="p-3">Kategoriya</th><th className="p-3">Qadoq / korobka</th><th className="p-3">Narx</th><th className="p-3">Holat</th><th className="p-3"></th></tr></thead><tbody className="divide-y divide-slate-100">{products.map((product) => <tr key={product.id}><td className="p-3 font-mono">{product.sku}</td><td className="p-3 font-medium">{product.translations.find((translation) => translation.locale === 'uz')?.name}</td><td className="p-3 text-slate-500">{categoryName.get(product.categoryId)}</td><td className="p-3">{product.unitsPerPack} / {product.unitsPerCarton}</td><td className="p-3">{product.publicPrice == null ? 'So‘rov' : Number(product.publicPrice).toLocaleString('uz-UZ')}</td><td className="p-3 text-slate-500">{product.availabilityStatus}</td><td className="p-3"><div className="flex gap-2"><button onClick={() => edit(product)} className="p-2 text-blue-400" aria-label="Tahrirlash"><Edit3 size={17} /></button><button onClick={() => void archive(product.id)} className="p-2 text-red-400" aria-label="Arxivlash"><Archive size={17} /></button></div></td></tr>)}</tbody></table>}</div>
  </div>;
}
