'use client';
import React, { useState } from 'react';
import { CheckCircle2, Download, FileSpreadsheet, Loader2, Upload } from 'lucide-react';

interface ImportResult { totalRows?: number; validRows?: number; errorRows?: number; importedRows?: number; jobId?: string; errors?: Array<{ rowNumber: number; field?: string; message: string }> }

export default function AdminProductImport() {
  const [file, setFile] = useState<File | null>(null); const [loading, setLoading] = useState(false); const [result, setResult] = useState<ImportResult | null>(null); const [error, setError] = useState('');
  const upload = async (mode: 'preview' | 'commit') => { if (!file) return; setLoading(true); setError(''); const form = new FormData(); form.set('file', file); form.set('mode', mode); try { const response = await fetch('/api/admin/import/products', { method: 'POST', body: form }); const data = await response.json(); setResult(data); if (!response.ok) throw new Error(data.error || 'Import xatoligi'); } catch (uploadError) { setError(uploadError instanceof Error ? uploadError.message : 'Import xatoligi'); } finally { setLoading(false); } };
  return <div className="mx-auto max-w-4xl space-y-6"><div><h2 className="text-2xl font-bold">Excel / CSV import</h2><p className="text-sm text-slate-500">Avval dry-run tekshiruvi, keyin xatosiz faylni bazaga yozish</p></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-col items-center rounded-2xl border-2 border-dashed border-slate-200 p-10 text-center"><FileSpreadsheet size={42} className="mb-3 text-emerald-400" /><p className="font-semibold">CSV yoki XLSX faylni tanlang</p><p className="mt-1 text-xs text-slate-400">Maksimal 10MB va 5000 qator</p><input type="file" accept=".csv,.xlsx" onChange={(event) => { setFile(event.target.files?.[0] || null); setResult(null); }} className="mt-5 text-sm" />{file && <p className="mt-3 text-sm text-red-600">{file.name}</p>}</div>
      <div className="mt-5 flex flex-wrap gap-3"><a href="/api/admin/import/products?template=csv" className="flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm"><Download size={17} /> CSV shablon</a><button disabled={!file || loading} onClick={() => void upload('preview')} className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold disabled:opacity-50">{loading ? <Loader2 className="animate-spin" size={17} /> : <Upload size={17} />} Dry-run</button>{result && (result.errorRows || 0) === 0 && (result.validRows || 0) > 0 && <button disabled={loading} onClick={() => void upload('commit')} className="flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold"><CheckCircle2 size={17} /> Bazaga yozish</button>}</div>
    </div>
    {error && <div className="rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-red-300">{error}</div>}
    {result && <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="grid grid-cols-3 gap-3 text-center"><div className="rounded-xl bg-slate-50 p-3"><p className="text-2xl font-bold">{result.totalRows ?? result.importedRows ?? 0}</p><p className="text-xs text-slate-400">Jami</p></div><div className="rounded-xl bg-emerald-500/10 p-3"><p className="text-2xl font-bold text-emerald-400">{result.validRows ?? result.importedRows ?? 0}</p><p className="text-xs text-slate-400">To‘g‘ri</p></div><div className="rounded-xl bg-red-500/10 p-3"><p className="text-2xl font-bold text-red-400">{result.errorRows || 0}</p><p className="text-xs text-slate-400">Xato</p></div></div>{result.jobId && <p className="mt-4 text-sm text-emerald-400">Import tugadi. Job: {result.jobId}</p>}{result.errors?.length ? <div className="mt-4 max-h-72 overflow-auto rounded-xl border border-slate-200"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-2">Qator</th><th className="p-2">Maydon</th><th className="p-2">Xato</th></tr></thead><tbody>{result.errors.map((item, index) => <tr key={`${item.rowNumber}-${index}`} className="border-t border-slate-100"><td className="p-2">{item.rowNumber}</td><td className="p-2">{item.field}</td><td className="p-2 text-red-300">{item.message}</td></tr>)}</tbody></table></div> : null}</div>}
  </div>;
}
